[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
polysite = { path = "../" }
tokio = { version = "1", features = ["full"] }

[[example]]
name = "simple_markdown"
path = "simple_markdown.rs"
